import { Conditions } from "@/app/types/weather";

const conditionAnimations = {
  [Conditions.CLEAR_DAY]: "/assets/img/clear-day.svg",
  [Conditions.CLEAR_NIGHT]: "/assets/img/clear-night.svg",
  [Conditions.CLOUDY]: "/assets/img/cloudy.svg",
  [Conditions.OVERCAST_DAY]: "/assets/img/overcast-day.svg",
  [Conditions.OVERCAST_NIGHT]: "/assets/img/overcast-night.svg",
  [Conditions.PARTLY_CLOUDY_DAY]: "/assets/img/partly-cloudy-day.svg",
  [Conditions.PARTLY_CLOUDY_DAY_DRIZZLE]: "/assets/img/partly-cloudy-day-drizzle.svg",
  [Conditions.PARTLY_CLOUDY_DAY_HAIL]: "/assets/img/partly-cloudy-day-hail.svg",
  [Conditions.PARTLY_CLOUDY_DAY_RAIN]: "/assets/img/partly-cloudy-day-rain.svg",
  [Conditions.PARTLY_CLOUDY_DAY_SLEET]: "/assets/img/partly-cloudy-day-sleet.svg",
  [Conditions.PARTLY_CLOUDY_DAY_SNOW]: "/assets/img/partly-cloudy-day-snow.svg",
  [Conditions.PARTLY_CLOUDY_DAY_FOG]: "/assets/img/partly-cloudy-day-fog.svg",
  [Conditions.PARTLY_CLOUDY_DAY_HAZE]: "/assets/img/partly-cloudy-day-haze.svg",
  [Conditions.PARTLY_CLOUDY_NIGHT]: "/assets/img/partly-cloudy-night.svg",
  [Conditions.PARTLY_CLOUDY_NIGHT_DRIZZLE]: "/assets/img/partly-cloudy-night-drizzle.svg",
  [Conditions.PARTLY_CLOUDY_NIGHT_HAIL]: "/assets/img/partly-cloudy-night-hail.svg",
  [Conditions.PARTLY_CLOUDY_NIGHT_RAIN]: "/assets/img/partly-cloudy-night-rain.svg",
  [Conditions.PARTLY_CLOUDY_NIGHT_SLEET]: "/assets/img/partly-cloudy-night-sleet.svg",
  [Conditions.PARTLY_CLOUDY_NIGHT_SNOW]: "/assets/img/partly-cloudy-night-snow.svg",
  [Conditions.PARTLY_CLOUDY_NIGHT_FOG]: "/assets/img/partly-cloudy-night-fog.svg",
  [Conditions.PARTLY_CLOUDY_NIGHT_HAZE]: "/assets/img/partly-cloudy-night-haze.svg",
  [Conditions.DRIZZLE]: "/assets/img/drizzle.svg",
  [Conditions.HAIL]: "/assets/img/hail.svg",
  [Conditions.RAIN]: "/assets/img/rain.svg",
  [Conditions.SLEET]: "/assets/img/sleet.svg",
  [Conditions.SNOW]: "/assets/img/snow.svg",
  [Conditions.WIND]: "/assets/img/wind.svg",
  [Conditions.MIST]: "/assets/img/mist.svg",
  [Conditions.THUNDERSTORMS]: "/assets/img/thunderstorms.svg",
  [Conditions.THUNDERSTORMS_RAIN]: "/assets/img/thunderstorms-rain.svg",
  [Conditions.THUNDERSTORMS_SNOW]: "/assets/img/thunderstorms-snow.svg",
  [Conditions.THUNDERSTORMS_DAY]: "/assets/img/thunderstorms-day.svg",
  [Conditions.THUNDERSTORMS_DAY_RAIN]: "/assets/img/thunderstorms-day-rain.svg",
  [Conditions.THUNDERSTORMS_DAY_SNOW]: "/assets/img/thunderstorms-day-snow.svg",
  [Conditions.THUNDERSTORMS_NIGHT]: "/assets/img/thunderstorms-night.svg",
  [Conditions.THUNDERSTORMS_NIGHT_RAIN]: "/assets/img/thunderstorms-night-rain.svg",
  [Conditions.THUNDERSTORMS_NIGHT_SNOW]: "/assets/img/thunderstorms-night-snow.svg",
  [Conditions.FOG]: "/assets/img/fog.svg",
  [Conditions.FOG_DAY]: "/assets/img/fog-day.svg",
  [Conditions.FOG_NIGHT]: "/assets/img/fog-night.svg",
  [Conditions.HAZE]: "/assets/img/haze.svg",
  [Conditions.HAZE_DAY]: "/assets/img/haze-day.svg",
  [Conditions.HAZE_NIGHT]: "/assets/img/haze-night.svg",
};

export const getConditionAnimation = (condition: Conditions) => {
  return conditionAnimations[condition as Conditions];
};
